title: Manny Express
email: mannyexpress11@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Service de déménagement professionnel et rapide. Tarifs compétitifs, équipe expérimentée.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mannyexpress.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
